version: '3'

services:
  froxlor:
    image: bloodhunterd/froxlor
    ports:
      - '80'
      - '443'
    restart: unless-stopped
    volumes:
      - ./froxlor/:/var/www/froxlor/
      - ./customers/:/var/customers/
      - ./ssl/:/etc/ssl/froxlor/
